
scrape_configs:

  - job_name: "node_exporter"
    static_configs:
      - targets: ["192.168.0.193:9100"]
        labels:
          server: "server-195"

  - job_name: "cadvisor"
    static_configs:
      - targets: ["192.168.0.193:8080"]
        labels:
          server: "server-195"